# Default image for all jobs unless overridden
image: node:18

stages:
  - build
  - test
  - deploy    # Add new deploy stage

build_website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
      - ./public

test_artifact:
  stage: test
  image: alpine    # Override default image
  script:
    - grep -q "Gatsby" ./public/index.html

test_website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve & 
    - sleep 3
    - curl localhost:9000 | tac | tac | grep -q "Gatsby"

deploy_to_surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain slimy-silk123.surge.sh