stages:
  - build
  - test

build_website:
  image: node:18
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public  

test_artifact:
  stage: test
  image: alpine
  script:
    - grep -q "Gatsby" ./public/index.html

test_website:
  stage: test
  image: node
  script:
    - npm install
    - npm -g install gatsby-cli
    - gatsby serve
    - sleep 3
    - curl localhost:9000  | grep -q "Gatsby"